"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { pingGoogleSitemap } from "@/app/actions/seo";
import { SectionCard } from "@/components/admin/pages/shared/SectionCard";
import { Button } from "@/components/ui/button";

export function SitemapAdminClient({
  siteUrl,
  staticRoutes,
}: {
  siteUrl: string;
  staticRoutes: string[];
}) {
  const [pending, startTransition] = useTransition();
  const [resultMessage, setResultMessage] = useState<string | null>(null);
  const sitemapUrl = `${siteUrl.replace(/\/+$/, "")}/sitemap.xml`;

  function ping() {
    startTransition(async () => {
      const result = await pingGoogleSitemap();
      setResultMessage(result.message);
      if (result.success) {
        toast.success(result.message);
      } else {
        toast.message(result.message);
      }
    });
  }

  return (
    <div className="space-y-4">
      <SectionCard
        title="Public sitemap"
        description="The live sitemap is generated by the website and includes static pages, published resources, categories, and tags — excluding redirected or noindex paths."
      >
        <p className="mono text-sm text-[var(--color-foreground)]">{sitemapUrl}</p>
        <p className="text-sm text-[var(--color-muted)]">
          Typical static entries (subject to SEO include/index flags):
        </p>
        <ul className="max-h-64 space-y-1 overflow-y-auto rounded-xl border border-[var(--color-border)] bg-[var(--color-surface-strong)] p-3 font-mono text-xs text-[var(--color-muted)]">
          {staticRoutes.map((route) => (
            <li key={route || "/"}>{route || "/"}</li>
          ))}
          <li>/resources/[slug]</li>
          <li>/categories/[slug]</li>
          <li>/tags/[slug]</li>
        </ul>
      </SectionCard>

      <SectionCard
        title="Notify Google"
        description="Google deprecated sitemap ping. This action reports the real response and recommends Search Console when ping is unavailable."
      >
        <Button onClick={ping} disabled={pending}>
          {pending ? "Pinging…" : "Ping Google sitemap"}
        </Button>
        {resultMessage ? (
          <p className="mt-3 text-sm text-[var(--color-muted)]">{resultMessage}</p>
        ) : null}
      </SectionCard>
    </div>
  );
}
